/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
typedef volatile unsigned int vuint32_t;


#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(vuint32_t *)(GPIOA_BASE+0x04)
#define GPIOA_ODR *(vuint32_t *)(GPIOA_BASE+0x0C)

#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE+0x18)
#define GPIOA_RCC 2

int main(void)
{

	//GPIOA CLOCK ENABLED
	RCC_APB2ENR|=1<<GPIOA_RCC;


	GPIOA_CRH &=0xFF0FFFFF;
	GPIOA_CRH |=0x00200000;

	while(1)
	{
		GPIOA_ODR|=1<<13;
		for(int i=0;i<5000;i++);
		GPIOA_ODR&=~(1<<13);
		for(int i=0;i<5000;i++);

	}
}
