/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "Platform_types.h"
#include "Mem_Map.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{


	RCC_APB2ENR|=1<<2;
	PORTA_Mode->pin.Pin8=0;
	PORTA_Mode->pin.Pin8=2;

	while(1)
	{
		PORTA_Data->pin.Pin8=1;
		for(uint32 i=0;i<500000;i++);
		PORTA_Data->pin.Pin8=0;
		for(uint32 i=0;i<500000;i++);
	}

	return 0;
}
