/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Lab1Registers.h"


int main(void)
{

	SET_BIT(RCC_APB2ENR,2);
	CLEAR_BYTE(PORTA_CRH,20);
	SET_BIT(PORTA_CRH,21);

	for(;;)
	{
		R_ODR_t->pin.pin13=1;
		for(uint64 i=0;i<50000;i++);
		R_ODR_t->pin.pin13=0;
		for(uint64 i=0;i<50000;i++);
	}
}
